repos:
  - repo: https://github.com/psf/black
    rev: 21.4b0  # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3.9 # Should be a command that runs python3.9+