[tool.black]
target-version = ['py36', 'py37']
skip-string-normalization = true
exclude = '''(copylot/hardware/mirrors/optotune/optoMDC)'''

[build-system]
requires = [
  "setuptools >= 42",
  "wheel",
  "setuptools_scm[toml]>=3.4"
]

[tool.setuptools_scm]
write_to = "copylot/_version.py"
