name: dorado
hardware:
  - ni_daq:
      show_gui: true
  - filterwheel:
      show_gui: false
      com_port: "COM8"
  - coherent_laser:
      show_gui: true
  - orca_camera:
      TRIGGER_MODE: "NORMAL"
      TRIGGERPOLARITY: "POSITIVE"
      TRIGGER_CONNECTOR: "BNC"
      TRIGGERTIMES: 1
      TRIGGERDELAY: 0
      TRIGGERSOURCE: "EXTERNAL"
      TRIGGERACTIVE: "SYNCREADOUT"
