name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest
    if: github.repository == 'czbiohub/coPylot'

    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.12.0
      - name: Check code styling with Black
        run: |
          black --diff -S -t py39 copylot
          black --check -S -t py39 copylot

  lint:
      name: Lint Check
      runs-on: ubuntu-latest
      if: github.repository == 'czbiohub/coPylot'

      strategy:
        matrix:
          python-version: [ 3.9 ]

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements/development.txt
            pip install -e .
        - name: Check code with Flake8
          run: |
            flake8 copylot
        - name: Check code with pylint
          run: |
            pylint copylot

  test-linux:
    needs: [ style, lint ]
    name: Tests
    runs-on: ubuntu-latest
    if: github.repository == 'czbiohub/coPylot'

    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest==6.2.5
      - name: Run the tests
        run: |
          python -m pytest . --disable-pytest-warnings --durations=30 --show-capture=stderr
